name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup
      run: |
        set -xe
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
        cachix use zarybnicky-cache

        nix build -L .#nixosConfigurations.charlie.config.system.build.toplevel
        echo ./result | cachix push -j8 zarybnicky-cache
        echo "RESULT=$(realpath result)" >> $GITHUB_ENV

        set +xe
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/deploy_key
        cat > ~/.ssh/config <<EOS
        Host deploy
        Hostname ${{ secrets.HOST }}
        User iot
        IdentityFile ~/.ssh/deploy_key
        set -xe

        nix copy -s --to ${{ secrets.HOST }} ./result
        ssh -o StrictHostKeyChecking=no secrets.HOST 2>&1 <<EOS
          sudo $(realpath ./result)/bin/switch-to-configuration switch
          sudo nix-env --profile /nix/var/nix/profiles/system --set $(realpath ./result)
        EOS
