name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup
      run: |
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
        cachix use zarybnicky-cache
    - name: Build & push
      run: |
        nix build -L .#nixosConfigurations.charlie.config.system.build.toplevel
        echo ./result | cachix push -j8 zarybnicky-cache
    - name: Deploy
      run: |
        echo "$SSH_PRIVATE_KEY" > ../private.key
        chmod 600 ../private.key
        mkdir -p ~/.ssh/
        ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
        export SSHOPTS="-i ../private.key"
        result/sw/bin/nixos-rebuild --target-host ${{ secrets.HOST }} --build-host localhost --flake .#charlie switch
